version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  ppm-mon:

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - ppm-mon
    restart: always

  # Uncomment to enable grafana
  # grafana:
  #   image: grafana/grafana
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #     - ./grafana/provisioning/:/etc/grafana/provisioning/
  #   env_file:
  #     - ./grafana/config.monitoring
  #   networks:
  #     - ppm-mon
  #   restart: always

  ppm-mon:
    build: .
    depends_on:
      - prometheus
    # ports:
    #   - 8000:8000
    networks:
      - ppm-mon
    restart: always
    environment:
      TWITCH_TOKEN: 'PUT_YOUR_TOKEN_HERE'
      TWITCH_NICKNAME: 'PUT_YOUR_NICKNAME_HERE'
      TWITCH_CHANNEL: '#PUT_YOUR_CHANNEL_HERE'
