{
 "title": "Emotes Mon",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "fr_emote",
    "label": "FR Emote",
    "query": "cogFR,cuteFR,chokeFR,dinkFR,djFR,evilFR,ezFR,fallFR,feelsFR,FRpls,grinFR,Hapje,happyFR, hugFR,jumpFR,ladderFR,loveFR,LFRW,LPPM, ,MEGALUL,pauseFR,popFR,pteraFR,puzzleFR,ratFR,frunFR,Saje,spinFR,stealthFR,suitFR,swimFR,tripFR,trollFR,WAYTOOFR,wiggleFR"
   }
  ]
 },
 "panels": [
  {
   "title": "FR Emote stat and Comparasing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(emote_usage_total{emote='$fr_emote'}[1y])) by (emote))",
     "legendFormat": "{{emote}}"
    }
   ]
  },
  {
   "title": "FR Emotes",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(emote_usage_total[1y])) by (emote))",
     "legendFormat": "{{emote}}"
    }
   ]
  },
  {
   "title": "Top 5",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(5, sum by (emote) (increase(emote_usage_total[1y])))",
     "legendFormat": "{{emote}}"
    }
   ]
  },
  {
   "title": "Last 5",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "bottomk(5, sum by (emote) (increase(emote_usage_total[1y])))",
     "legendFormat": "{{emote}}"
    }
   ]
  }
 ]
}